apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: ingress-srv
    annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: posts.com
      http:
        paths:
          - path: /api/users/?(.*)
            pathType: Prefix
            backend:
              serviceName: auth-srv
              servicePort: 3000
          - path: /?(.*)
            pathType: Prefix
            backend:
              serviceName: client-srv
              servicePort: 3000
